
server:
  port: 8081
  servlet:
    context-path: /webapp

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/./sct_db
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: SystemCityTransport

bot:
  name: System City Transport
  token: 5205892453:AAGYV814UPU6B5Crv66nY1wlC8rX7MiYssM
  beginBalance: 500